[package]
name = "ts-schema"
version = "0.1.0"
edition = "2024"

[dependencies]
swc_common = { version = "8.1.1", features = ["tty-emitter"] }
swc_ecma_parser = { version = "11.1.3", features = ["typescript"] }
